name: Build

on:
  pull_request:

jobs:
  ####### Check files and formatting #######

  check-copyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Find un-copyrighted files
        run: |
          find . -name '*.rs' -exec grep  -H -E -o -c Copyright {} \; | grep ':0' || true
          FILECOUNT=$(find . -name '*.rs' -exec grep  -H -E -o -c  'Copyright'  {} \; | grep -c ':0' || true)
          if [[ $FILECOUNT -eq 0 ]]; then
            true
          else
            false
          fi

  check-editorconfig:
    name: "Check editorconfig"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup editorconfig checker
        run: |
          ls /tmp/bin/ec-linux-amd64 || \
          cd /tmp && \
          wget https://github.com/editorconfig-checker/editorconfig-checker/releases/download/2.1.0/ec-linux-amd64.tar.gz && \
          tar xvf ec-linux-amd64.tar.gz && \
          chmod +x bin/ec-linux-amd64
      - name: Check files
        run: /tmp/bin/ec-linux-amd64

  check-rust-fmt:
    name: "Check with rustfmt"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      # With rustup's nice new toml format, we just need to run rustup show to install the toolchain
      # https://github.com/actions-rs/toolchain/issues/126#issuecomment-782989659
      - name: Setup Rust toolchain
        run: rustup show
      - name: Format code with rustfmt
        run: ./scripts/exec-each-runtime.sh "cargo fmt -- --check"

  ####### TODO: Building and Testing rust code #######

  ####### Verifying runtimes wasm blobs #######
  check-runtimes-wasm-blobs:
    name: "Check runtimes wasm blobs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            tracing_47:
              - 'tracing/47/**'
            tracing_49:
              - 'tracing/49/**'
            tracing_52:
              - 'tracing/52/**'
            tracing_53:
              - 'tracing/53/**'
            tracing_155:
              - 'tracing/155/**'
            tracing_300:
              - 'tracing/300/**'
            tracing_400:
              - 'tracing/400/**'
      - name: "Check runtimes tracing/47"
        if:  steps.filter.outputs.tracing_47 == 'true'
        run: |
          EXPECTED_HASH=cat srtool-digest/moonbase-runtime-47-substitute-tracing.json | jq -r .sha256
          ./scripts/build-tracing-runtime.sh 47
          ACTUAL_HASH=cat srtool-digest/moonbase-runtime-47-substitute-tracing.json | jq -r .sha256
          if [ "$EXPECTED_HASH" -ne "$ACTUAL_HASH" ]; then
            exit 1
          fi

